FROM ghcr.io/fwcd/archlinux
RUN pacman -Syu --needed --noconfirm base-devel cmake git glslang libzip mbedtls ninja zip unzip wget vulkan-headers
WORKDIR /root
RUN wget https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.6%2B7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.6_7.tar.gz -O OpenJDK.tar.gz
RUN tar xzf OpenJDK.tar.gz
RUN rm OpenJDK.tar.gz
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O commandlinetools.zip
RUN mkdir -p ~/Android/Sdk/cmdline-tools
RUN unzip commandlinetools.zip -d ~/Android/Sdk/cmdline-tools
RUN rm commandlinetools.zip
RUN mv ~/Android/Sdk/cmdline-tools/cmdline-tools ~/Android/Sdk/cmdline-tools/latest
ENV JAVA_HOME=$HOME/jdk-21.0.6+7
ENV PATH=$PATH:$JAVA_HOME/bin
ENV ANDROID_SDK_ROOT=$HOME/Android/Sdk
ENV PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
ENV PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
RUN yes | sdkmanager --licenses
RUN mkdir -p outputs
COPY citron_android.sh build.sh
ENTRYPOINT ["/root/build.sh"]