FROM ghcr.io/fwcd/archlinux
RUN pacman -Syu --needed --noconfirm base-devel cmake git glslang libzip mbedtls ninja zip unzip qt5 sdl3 gst-plugins-bad
WORKDIR /root
RUN mkdir -p outputs
COPY torzu_linux.sh build.sh
ENTRYPOINT ["/root/build.sh"]